- hosts: all
  tasks:
    - name: Update and install nginx
      become: true
      ansible.builtin.apt:
        name:
        - nginx
        state: latest
        update_cache: yes
    - name: Start Nginx
      become: true
      become_method: sudo
      ansible.builtin.service:
        name: nginx
        state: started
    # - name: Print facts
    #   ansible.builtin.debug:
    #     var: ansible_facts.hostname
    - name: Delete file
      become: true
      become_method: sudo
      file:
        path: /var/www/html/index.html
        state: absent    
    - name: Templating index.html
      become: true
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
    - name: Ensure that Nginx service is running
      become: true
      become_method: sudo
      ansible.builtin.service:
        name: nginx
        state: reloaded
    - name: Register nginx version
      ansible.builtin.command: nginx -v
      register: nginx_version
      changed_when: false
    - name: Display version
      ansible.builtin.debug: msg={{nginx_version.stderr_lines}}
